/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-04-16 08:52:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.myweb.user.model.UserVO;
import com.myweb.user.model.UserDAO;

public final class user_005fupdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/user/../include/footer.jsp", Long.valueOf(1713162932531L));
    _jspx_dependants.put("/user/../include/header.jsp", Long.valueOf(1713170027002L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.myweb.user.model.UserDAO");
    _jspx_imports_classes.add("com.myweb.user.model.UserVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	if(session.getAttribute("user_id")==null) {
		response.sendRedirect("user_login.jsp");
	}

	String id = (String)session.getAttribute("user_id");

	UserDAO dao = UserDAO.getInstance();
	UserVO vo = dao.getUserInfo(id);


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("	    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("	    <meta name=\"viewport\" content=\"width=device-idth, initial-scale=1\">\r\n");
      out.write("	   \r\n");
      out.write("	\r\n");
      out.write("	    <title>Welcome to MyWorld</title>\r\n");
      out.write("	\r\n");
      out.write("	    <!-- Bootstrap Core CSS -->\r\n");
      out.write("	    <link href=\"../css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("	\r\n");
      out.write("	    <!-- Custom CSS -->\r\n");
      out.write("	    <link href=\"../css/business-casual.css\" rel=\"stylesheet\">\r\n");
      out.write("	\r\n");
      out.write("	    <!-- Fonts -->\r\n");
      out.write("	    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("	    <link href=\"https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("		\r\n");
      out.write("		 <!-- jQuery -->\r\n");
      out.write("	    <script src=\"../js/jquery.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	    <!-- Bootstrap Core JavaScript -->\r\n");
      out.write("	    <script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("	<!-- header -->\r\n");
      out.write("	<div class=\"brand\">My Web</div>        \r\n");
      out.write("    <div class=\"address-bar\">Welcome to MyWorld</div>\r\n");
      out.write("		\r\n");
      out.write("    \r\n");
      out.write("    <nav class=\"navbar navbar-default\" role=\"navigation\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                \r\n");
      out.write("                <a class=\"navbar-brand\" href=\"/hong\">My First Web</a>\r\n");
      out.write("            </div>\r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("                <ul class=\"nav navbar-nav\">\r\n");
      out.write("                	\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"/myweb/index.jsp\">HOME</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"/myweb/member/member.jsp\">Member</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"/myweb/board/list.board\">BOARD</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    ");
if (session.getAttribute("user_id")==null) {
      out.write("\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"/myweb/user/user_login.jsp\">LOGIN</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"/myweb/user/user_join.jsp\" style=\"color:red\">JOIN</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    ");
}else{ 
      out.write("\r\n");
      out.write("                    <li>\r\n");
      out.write("                    	<a href=\"/myweb/user/user_logout.jsp\">LOGOUT</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                    	<a href=\"/myweb/user/user_mypage.jsp\" style=\"color:red\">MaPage</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    ");
} 
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <!-- /.navbar-collapse -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.container -->\r\n");
      out.write("    </nav>\r\n");
      out.write(" 	<!-- end header -->");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("		<section>\r\n");
      out.write("			<div align=\"center\">\r\n");
      out.write("				<form name=\"regform\" action=\"user_update_ok.jsp\" method=\"post\">\r\n");
      out.write("					<h2>회원정보 수정 페이지</h2>\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>아이디</td>\r\n");
      out.write("							<td><input type=\"text\" name=\"id\" value=\"");
      out.print(id );
      out.write("\" readonly></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>이름</td>\r\n");
      out.write("							<td><input type=\"text\" name=\"name\" value=\"");
      out.print(vo.getName() );
      out.write("\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>이메일</td>\r\n");
      out.write("							<td><input type=\"email\" name=\"email\" value=\"");
      out.print(vo.getEmail() );
      out.write("\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>주소</td>\r\n");
      out.write("							<td><input type=\"text\" name=\"address\" value=\"");
      out.print(vo.getAddress() );
      out.write("\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("					<br><br>\r\n");
      out.write("					<input type=\"button\" value=\"정보수정\" class=\"btn btn-primary\" onclick=\"check()\">\r\n");
      out.write("					<input type=\"button\" value=\"마이페이지\" class=\"btn btn-info\" onclick=\"location.href='user_mypage.jsp'\">\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("	    \r\n");
      out.write("	    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12 text-center\">\r\n");
      out.write("                    <p>Copyright &copy; By Jo 2024.04.15</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>");
      out.write("\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("			function check() {\r\n");
      out.write("				//form은 유일하게 document.태그이름으로 접근 가능... \r\n");
      out.write("				if( document.regform.name.value == '') {\r\n");
      out.write("					alert(\"이름은 필수 사항입니다.\")\r\n");
      out.write("					return;\r\n");
      out.write("				}else if( confirm(\"회원 정보을 수정하시겠습니까?\")) {\r\n");
      out.write("					// confirm() 확인창을 띄워서 확인(true)/취소(false) 중 선택하는 메서드\r\n");
      out.write("					document.regform.submit();  //자바스크립트의 submit 기능\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		</script>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
